"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import AuthGuard from "@/components/AuthGuard";
import { api } from "@/lib/api";

function AdminContent(){const[health,setHealth]=useState<any>(null);const[metrics,setMetrics]=useState<any>(null);useEffect(()=>{api.health().then(setHealth).catch(()=>{});api.dashboard().then(setMetrics).catch(()=>{});},[]);return <>
  <div className="page-head"><div><div className="eyebrow">SYSTEM ADMINISTRATION</div><h1>Administrator panel</h1><p>Govern access, policy, automation health, and ward-wide service configuration.</p></div><span className="badge critical">Privileged role</span></div>
  <div className="kpis"><div className="kpi"><span className="metric-label">API & agents</span><b style={{fontSize:24}}>Operational</b><span className="trend">AWS ap-south-1</span></div><div className="kpi"><span className="metric-label">Reports</span><b>{metrics?.total??"—"}</b><span className="trend">Tenant total</span></div><div className="kpi"><span className="metric-label">Notification failures</span><b>{health?.recent_notification_failures??"—"}</b><span className="trend">Recent window</span></div><div className="kpi"><span className="metric-label">Privacy mode</span><b style={{fontSize:24}}>Enforced</b><span className="trend">Aggregate public data</span></div></div>
  <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h3>Administration modules</h3><p>Changes here affect the full tenant.</p></div></div><div className="admin-module-grid"><Link href="/settings" className="pathway-card"><span className="pathway-icon">⚙</span><div><h3>Policy & routing</h3><p>Configure SLA, department routing, contacts, and priority weights.</p><b>Open policy →</b></div></Link><Link href="/admin/health" className="pathway-card"><span className="pathway-icon">⌁</span><div><h3>Agent health</h3><p>Inspect scheduler heartbeat and delivery health.</p><b>Open diagnostics →</b></div></Link><Link href="/officer" className="pathway-card"><span className="pathway-icon">▤</span><div><h3>Operations</h3><p>Enter the operational workspace with administrator authority.</p><b>Open queue →</b></div></Link></div></section><aside className="panel"><div className="eyebrow">ROLE DIRECTORY</div><h3>Access model</h3><div className="role-list"><div><span className="badge resolved">Citizen</span><p>Public report and private tracking</p></div><div><span className="badge open">Officer</span><p>Ward-scoped case operations</p></div><div><span className="badge high">Coordinator</span><p>Read-only service supervision</p></div><div><span className="badge critical">Administrator</span><p>Policy and system control</p></div></div></aside></div>
  </>}
export default function AdminPanel(){return <AuthGuard roles={["admin"]}><AdminContent/></AuthGuard>}
